FROM alpine  
#ALPINE is light weight operating system.   
#RUN apk add --update redis 
# package manager automaticaly downlado softwre redis and install. (Creates temp contaner with alpine and  downlaod solftware.
RUN apk add --update gcc 

RUN apk add --update redis 
CMD ["redis-server"]

